### ISSUE TITLE
DoubleClickCrypto not really threadsafe?

### ISSUE THREAD

**Issue by aeneid** [google/openrtb-doubleclick#100]
DoubleClickCrypto defines a ThreadLocalRandom member this way:
```
private final ThreadLocalRandom fastRandom = ThreadLocalRandom.current();
```
It uses this ThreadLocalRandom to initialize an initVector whenever we wish to encrypt data.
This permanently sets the fastRandom member to the creating thread's ThreadLocalRandom.
ThreadLocalRandom is, by itself, not a thread-safe object and all uses of it should be of the form:
```
ThreadLocalRandom.current().nextX(...)
```

This makes DoubleClickCrypto essentially not thread-safe.
Am I missing anything?

**Comment by opinali** [comment]
You are right, this was a bad change... years ago so it's hard to remember/track if the racy random was intentional, it's not a big deal because we don't need a high quality rng here (not using `SecureRandom` for this reason), this method is mostly useful for tests since bidders never need to encrypt things. But there's certainly no motivation to make any sacrifice for correctness here, and if the racy random was desired we could just use a regular `Random`. I'm fixing this now. Thanks!

**Comment by aeneid** [comment]
I can provide a PR if you prefer

**Comment by opinali** [comment]
No need thanks, I just merged a commit for this, planning to release tomorrow.

**Comment by opinali** [comment]
Done, v1.2.3.
