### ISSUE TITLE
Geo Targeting - Mapping cities when postal codes is passed in the bid request

### ISSUE THREAD

**Issue by goavi** [google/openrtb-doubleclick#28]
Hi,

We've noticed that for postal codes entities the canonical name field in the geo-table doesn't include the city. For example:
In the bid request we're getting:
postal_code: "33611"
geo_criteria_id: 9012102
This maps to the following entry in the geo-able:
9012102,"33611","33611,Florida,United States","1015214,9040475,9057273,200539,21142,2840","","US","Postal Code"
In this case the GeoObject will not set the city attribute, which is Tampa (ID 1015214).
The implementation of the library seems to be using the canonical name and not looking at the parents column in order to fill the city, region and metro.

Is this planned to be supported? Is there a workaround for city targeting?

In the AdX pretargeting UI and in the Adwords UI I see that it does the matching between the zipcode and the city.

Thanks,
Avi.

**Comment by opinali** [comment]
You are correct, the problem is that the canonical name provides the State as the immediate parent of postal codes, thee's no city in-between like one would expect. I supposed that postal codes might not always be exclusive to cities; but then, there's no problem in the sequence of parent `geo_criteria_id`'s, in this case the first parent is 1015214 = Tampa. Unfortunately we don't use that sequence of IDs for building the child-parent relationships because, according to our documentation, *"This field is included for legacy support, and the IDs may not be consistent across datasets. Canonical Names is the preferred method of constructing hierarchies."* Let me investigate this.

**Comment by opinali** [comment]
Upon some extra investigation... the easiest way to fix this is by supporting both parent chains; here's what I'm doing: link the `GeoTarget` objects by both the canonical names and parent IDs, with separate pointers; provide APIs that allow to lookup the "parent/ancestor by canonical name" or "parent/ancestor by parent ID". The OpenRTB mapper can then try both chains, with priority for the canonical chain because it's the supported/recommended/best-quality data, but if we don't find what you want there then a result based on the parent ID chain is certainly more useful than nothing.

**Comment by opinali** [comment]
Implemented initially in this development fork:
https://github.com/opinali/openrtb-doubleclick/commit/b5eb2c47c0ca999def3d4cdd429df1f4f144b84e

**Comment by opinali** [comment]
Done https://github.com/google/openrtb-doubleclick/commit/53b9e63c6640aa9db6b9999169b487c111d20575
