### ISSUE TITLE
MapperUtil.toIpv4String truncates IPv4 addresses

### ISSUE THREAD

**Issue by dhamilton-nanigans** [google/openrtb-doubleclick#34]
I am using the openrtb-doubleclick library to convert AdX bid requests to OpenRtb requests, and am finding that it is failing to properly convert IPv4 ByteStrings. It seems that MapperUtil.toIpv4String is only iterating and converting the first three bytes in the IPv4 address, and padding the last one with a zero. The prevents DoubleClickOpenRtbMapper.toOpenRtbBidRequest from properly converting bid requests that contain IPv4 addresses.

Repro steps: 
MapperUtil.toIpv4String(ByteString.copyFrom(new byte[]{(byte) 0xC6, (byte) 0x8C, (byte) 0xCC, (byte) 0x74}))

Expected: "198.140.204.116"
Actual: "198.140.204.0"

**Comment by dhamilton-nanigans** [comment]
The fix should be to update line 86 of MapperUtil.java to:
    int size = min(**4**, bytes.size());

**Comment by opinali** [comment]
This limitation is purposeful. DoubleClick never sends you the complete IP address; for privacy reasons, we only send the first 3 octets for IPv4 or the first 12 for IPv6. You won't be ever able to map a DoubleClick's BidRequest.id to a value like "198.140.204.116" :-)

However, this line with the `min(4, ...)` seems unnecessary. It's just enforcing a limitation that is already enforced by the network protocol, perhaps in an attempt to be very general (not requiring that the parameter `ByteString` contain only the IP bytes) but that seems unnecessary, so I guess we can just remove the `min()` here and also in the IPv6 case. But that won't change anything in the mapping results.

Notice that the padding is required for compliance with the OpenRTB model, since the spec doesn't make a special provision for partial IP addresses, and a string like "198.140.204" is not a valid IP address, won't parse successfully on any API that handles IP addresses. Padding with 0 works since this creates a valid address that cannot be used by any host (it's the network identifier).

**Comment by dhamilton-nanigans** [comment]
You are right, that is my mistake. Sorry for any confusion.
