### ISSUE TITLE
Inconsistencies between adx-openrtb mapping and official adx documentation

### ISSUE THREAD

**Issue by MaliciousMustard** [google/openrtb-doubleclick#49]
Hi all,

We just noticed that the [adx-openRTB mapping](https://github.com/google/openrtb-doubleclick/blob/master/doubleclick-openrtb/src/main/resources/adx-openrtb/category-mapping-openrtb.txt) contains some inconsistencies with the [official documentation from Google](https://developers.google.com/ad-exchange/rtb/downloads). For example, in the mapping there is an Adx code 13003 which doesn't exist in the official documentation. 
Also, there are some values which exist in the official documentation but not in the mapping, for example Adx code 11950.

Can you shed some light over it?

Many thanks,
Alex & Massimo

**Comment by opinali** [comment]
The extra values happen because this category-mapping-openrtb file was created primarily for other Google products, including things that need to interop with other platforms like DBM. The categories used by the AdX protocol are a subset of those in this file, so maybe I should trim the file to only include what we need. But we should't have categories that exist in the AdX list but not here; I see in this specific example that actually, AdX 11950 corresponds to the 13003 here, the description is similar. Either way it looks inconsistent, thanks for finding this! I'll investigate the problem.

**Comment by bryan0817** [comment]
Agree with you that only subset is required here, eventually this project is for Adx.
There are also many mappings missing for sensitive category, ex: 
=========== List of sensitive categories openRTB <--> dcCatId : dcCatName =========
[[]] <--> 10 : Get Rich Quick
[[]] <--> 18 : Weight Loss

Here is the code to list current mapping results, hope it will help.
<pre><code>
import com.google.doubleclick.openrtb.AdCategoryMapper;
import com.google.doubleclick.util.DoubleClickMetadata;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.annotations.Test;
import java.util.Arrays;
import java.util.Iterator;
import java.util.Set;
public class DcCatMapResult {
    private static final Logger logger = LoggerFactory.getLogger(OpenRtbDoubleClickMapper.class);
    private static DoubleClickMetadata metadata;
    static {
        metadata = DoubleClickMapperUtil.getMetadata();
    }
    @Test
    public void listProductCat() {
        System.out.println("=============== List of product categories openRTB <--> dcCatId : dcCatName  =============");
        Iterator<Integer> keys = this.metadata.productCategories().keySet().iterator();
        while (keys.hasNext()) {
            int key = keys.next();
            Set cats = AdCategoryMapper.toOpenRtb(key);
            Arrays.asList(cats);
            System.out.println(Arrays.asList(cats) +" <--> "+ key + " : " +metadata.productCategories().get(key));
        }
    }
    @Test
    public void listSensitiveCat() {
        System.out.println("=============== List of sensitive categories openRTB <--> dcCatId : dcCatName =============");
        Iterator<Integer> keys = this.metadata.sensitiveCategories().keySet().iterator();
        while (keys.hasNext()) {
            int key = keys.next();
            Set cats = AdCategoryMapper.toOpenRtb(key);
            Arrays.asList(cats);
            System.out.println(Arrays.asList(cats) +" <--> "+ key + " : " +metadata.sensitiveCategories().get(key));
        }
    }
}</code></pre>

**Comment by opinali** [comment]
0.9.2 is out fixing this; following @bryan0817's idea there's also a new unit test that make sure all adx values are mapped, and if some is not, tries to suggest a mapping based on similar mappings. This turns out to save a lot of time since many of these categories are similar/redundant. This new unit test is disabled by default because it needs to fetch external files, which is slow/flaky.

Notice that some mappings are now unidirectional, for example "Get Rich Quick" maps to IAB26 / Illegal Content, but IAB26 will map to nothing. Not sure this has any practical consequence because you can't use that kind of category in adx pretargeting, anyway that's the mapping I could get vetted.
