### ISSUE TITLE
Carrier Name and App Categories mapping

### ISSUE THREAD

**Issue by fdeatilano** [google/openrtb-doubleclick#52]
Hi,

I have some concerns with this two fields. The mapping from "BidRequest.Mobile.carrier_id" to "OpenRtb.Device.carrier" leaves the carrier id provided by google, but that is not very useful if you don't convert it to the carrier name or standard code. I was wondering if it makes sense that this conversion would be covered by the DoubleClickMetadata class, like it is done with other CVS dictionaries. Specially because there is a link in the BidRequest message documentation pointing to a google hosted dictionary that covers that conversions (https://developers.google.com/adwords/api/docs/appendix/mobilecarriers).

The case of app categories is similar. In the DoubleClick <-> OpenRTB Mapping spreadsheet (https://docs.google.com/spreadsheets/d/1ormTUJziNQGnGEJcZJ4--NTa1IKi2dfgfzxBhc4oe9w) it is said that "DC.BidRequest.Mobile.app_category_ids" maps to "ORTB.App.cat", but that's not implemented in the library. Moreover the "BidRequest.Mobile.app_category_ids" documentation points to a dictionary with the google app categories IDs and names, but it does not provide a mapping to standard IAB names, which are the contents that should be stored in the ORTB.App.cat field. Maybe it would be useful to have a dictionary that maps App categories to IAB Content categories in the DoubleClickMetadata class too.

Thanks.

**Comment by opinali** [comment]
Not sure about using that to map the OpenRTB field. The problem is that the OpenRTB spec requires MNC codes, but our CSV doesn't include that... outside the US this gets messier, you need two codes (MCC + MNC) unless I map only the MNC and assume that users will use that as a compound key with the country from geo info. (And I wouldn't bet there's a 1:1 relationship of country:MCC.) Anyway AdX doesn't provide either MCCs or MNCs anywhere in the protocol or mapping files. But it makes sense to have this CSV loaded by `DoubleClickMetadata` to help users that don't want to deal with Google's carrier IDs.

Mobile app categories are a harder problem, we don't yet have a mapping table from the Google Play categories to IAB, this may take more time... the spreadsheet was filled in a bit optimistically for this field, for now I'm annotating it to make clear this is planned by not implemented yet.

**Comment by opinali** [comment]
Check out e1ca649e09fffc48ea28d388d53d495836c5b9b3

**Comment by fdeatilano** [comment]
I've reviewed the OpenRTB spec and it says this about carriers:

```carrier - string - Carrier or ISP (e.g., “VERIZON”). “WIFI” is often used in mobile
to indicate high bandwidth (e.g., video friendly vs. cellular).```

I agree that MNC + MCC code would be the best way to inform about the carrier, but in the meantime I think it's nearer to the standard to have the carrier name instead of the google carrier ID.

Thank you very much for the changes!
