### ISSUE TITLE
DoubleClickMetadata automatic use

### ISSUE THREAD

**Issue by Crystark** [google/openrtb-doubleclick#99]
Hi,

Is it possible to have the bid request automatically use the `DoubleClickMetadata` object ? I'm interested in having the carrier names instead of the google ids in my parsed bid request.
Thanks

**Comment by opinali** [comment]
That could be possible, the mapper is already configured with `DoubleClickMetadata`. But now the problem is that the mapper is completely gone in v1.2, we're not supporting client-side mapping anymore since native support for OpenRTB is now mature. This being an open source project, others are free to fork the last code before this change and keep maintaining the mapper but I think the benefit of doing that would be very marginal... for features like what you mention translating the carrier names, it seems much simpler to write an utility that processes the bid request object and only changes/adds some fields. (You can use `toBuilder()`, then traverse the tree and change whatever you want, then `build()`, the protobuf library makes this very efficient.)

**Comment by Crystark** [comment]
OK thanks, manual mapping it is ;)
